config:
  log:
    path: log/filesync.log
    rotation:
      max_size_mb: 10
      max_files: 5
  auth:
    - username: admin
      password: admin
  https:
    port: 8080
    cert_path_public: cert/server.crt
    cert_path_private: cert/server.key
  sync:
    schedule:
      - '* * * * *'

files:
  private: ../data/private/
  public: ../data/public/
  mirror:
    base_path: ../data/mirror
    data:
      unblock_lists:
        dnsmasq-nfset.lst: https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-dnsmasq-nfset.lst
      lampa:
        online_mod.js: https://nb557.github.io/plugins/online_mod.js
